//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myheroAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hero
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string review { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> age { get; set; }
    }
}
